const {
    VITE_PROJECT_ID_FOR_WALLET_CONNECT: PROJECT_ID_FOR_WALLET_CONNECT,
    VITE_DAPP_BASE_URL: DAPP_BASE_URL,
    VITE_HORIZON_NETWORK_PASSPHRASE: HORIZON_NETWORK_PASSPHRASE,
    VITE_STELLAR_NETWORK: STELLAR_NETWORK,
    VITE_HORIZON_URL: HORIZON_URL,
    VITE_SOROBANRPC_URL: SOROBANRPC_URL,
    VITE_GOOGLE_ANALYTICS_ID: GOOGLE_ANALYTICS_ID,
} = import.meta.env;

export {
    PROJECT_ID_FOR_WALLET_CONNECT,
    DAPP_BASE_URL,
    HORIZON_NETWORK_PASSPHRASE,
    STELLAR_NETWORK,
    HORIZON_URL,
    SOROBANRPC_URL,
    GOOGLE_ANALYTICS_ID,
};
